[package]
name = "phonk-wl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
image = "0.25.9"
rand = "0.9.2"
rodio = "0.21.1"
smithay-client-toolkit = "0.20.0"
wayland-client = "0.31.11"
wayland-protocols = "0.32.9"
